### ISSUE TITLE
Set the bot for listening when the poll is ended

### ISSUE THREAD

**Issue by heliomar-pena** [TeamNovaSoft/discord-bot#11]
This is: Make a command for create polls using the bot part 2

### Explanation

Once the votation is started with `/vote-points`, it should be listening to the changes of this votation to know when the poll is ended. 

Once the poll is ended, we would like to have the result of the votation presented as messages on the thread, one message for each point obtained for the development + 1 extra message mentioning `@TaskCompleted @user`. 

#### Expected Behaviour

Here is how it is working currently without the bot:

1. The space for giving the points is reserved creating empty messages (the various messages with .)
<img src="https://github.com/user-attachments/assets/bfe1d6b1-4391-43c7-a1a1-3a4aa5992e99" height="200px"/>

2. The votation start and we await until the votation end
<img src="https://github.com/user-attachments/assets/744d41d2-dfaa-4b9f-9253-dd99af7a25c3" height="200px"/>

3. Once the votation is ended, we add the points to the developer using `@`
<img src="https://github.com/user-attachments/assets/d3d4dc22-2197-49fc-b1a4-16a19f6f2e68" height="200px"/>

#### Technical Proposal

> [!TIP]
> Based on [this investigation](https://github.com/TeamNovaSoft/discord-bot/issues/2#issuecomment-2468496666), it seems like the only event that is near of this feature is `Event.MessagePollVoteAdd` and `Event.MessagePollVoteRemove`. 

1. When /vote-point command is invoked, the bot could send eight empty messages as we do (sending dots on the messages)
2. Then make the votation, as it does currently
3. Listen the event MessagePollVoteAdd and MessagePollVoteRemove
4. Each MessagePollVoteAdd check how many points should be given to the user, and assign them modifying empty messages. If points obtained are more than the points that have been given to the user, then edit the messages needed to make them match, if points obtained are less than the points that have been given to the user, then edit the messages needed to make them match
5. Each MessagePollVoteRemove, make the same that on step 4

### Checklist
 - [ ] When created votation, space for give points are reserver 
 - [ ] At the end of the poll, we have one (@addPoint @user) message for each point obtained for the user
 
### References

- https://github.com/discordjs/discord.js/blob/14.15.1/packages/discord.js/typings/index.d.ts#L5211
- https://discord.js.org/docs/packages/discord.js/14.15.1/Events:Enum

#### Related issues

- #2

**Comment by YoelFerreyra** [comment]
THis task is complete

**Comment by YoelFerreyra** [comment]
This task is complete
