### ISSUE TITLE
Bot automatic messages

### ISSUE THREAD

**Issue by heliomar-pena** [TeamNovaSoft/discord-bot#16]
### Explanation
 Sometimes the members of the server waits until someone say hello to say hello, so I think would be good if the bot automatically said hello, goodbye and enjoy lunch at specific hours of the day, so maybe people feels more confident about that

 This issue is to make the bot write in greetings channel and say: 
 
- 08AM COL: Good morning
- 12PM COL: Enjoy your lunch!
- 05PM COL: Have a nice afternoon, good job today!

 Those messages would only be sent on weekday and not on weekend

### Checklist
 
 - [ ] There are three messages at three different times:
    - [ ] 08 col:  "¡Buenos días a todos!"
    - [ ] 12 col: "¡Buen provecho!"
    - [ ] 17 col: ¡Feliz tarde a todos!, ¡Buen trabajo hoy!
- [ ] Hours are configurable on .env
- [ ] Message content are configurables on .env

**Comment by YoelFerreyra** [comment]
This task is complete
