### ISSUE TITLE
Check if logic on index.js for deploy commands and events can be moved to deploy-commands.js

### ISSUE THREAD

**Issue by heliomar-pena** [TeamNovaSoft/discord-bot#21]
### Explanation
 There is a file [deploy-commands.js](https://github.com/TeamNovaSoft/discord-bot/blob/main/src/deploy-commands.js) that is imported on [index.js](https://github.com/TeamNovaSoft/discord-bot/blob/main/src/index.js#L5), and seems like it does the same that index on [lines 15-30](https://github.com/TeamNovaSoft/discord-bot/blob/main/src/index.js#L15-L30).

 It seems like the bot is doing the job twice, loading commands twice. This task is to validate that, if that is the case, move the code that deploy commands on index.js to deploy-commands.js so we have index.js a bit more clean.

 Also, **create a new file** deploy-events and move the logic for deploy the events to this file instead of have it on index.js

### Screenshots
 
![image](https://github.com/user-attachments/assets/d184cf97-8810-4f2f-839a-d3dab61883c6)

### Checklist
 This issue can be closed when the following tasks are complete:

 - [ ] The logic for deploy commands and events are separated in files instead of be on index
 - [ ] All work as before
 - [ ] The bot is not doing the same work twice

**Comment by heliomar-pena** [comment]
I think the code on deploy-commands and the code on index do the same on that part, and we could move it completly to deploy-commands file. @YoelFerreyra do you know if it is actually like I say?

**Comment by joset98** [comment]
> I think the code on deploy-commands and the code on index do the same on that part, and we could move it completly to deploy-commands file. @YoelFerreyra do you know if it is actually like I say?

On theory it looks very similar, although both codes are necessary. I will try to unify both
