### ISSUE TITLE
Add new query on the command `/my-query-points`

### ISSUE THREAD

**Issue by heliomar-pena** [TeamNovaSoft/discord-bot#46]
### Explanation

My query points returns you the queries to check your points of the week, year, etc... This command returns like three queries: one is for Add Point, other for Add Boosted Points and other for Task Completed. Was missed the query `Author: @user` that works for get the PRs opened by the user

### Checklist

- [ ] When call /my-query-points returns the query `Author: @user`. And using that query I can know how many PRs the user opened on a period of time.

**Comment by joset98** [comment]
I check the command and saw that the last id in the response correspond to the `author_id`
>![image](https://github.com/user-attachments/assets/bfb16d78-b70e-45ef-a42a-3ee50a3d2474)

As we could see is in the code the author of the pr:
>![image](https://github.com/user-attachments/assets/6d787a39-d43b-4d19-bc46-2a3266adf49f)

So i am not sure about what is the requirement in this iss. Please could you explain more. Thank you!
